- meeting-notes/2023-05-03.md
> Notes from first meeting

- .mailmap
Add a .mailmap file to merge different contributor emails in the git
history.
> add mailmap file

- code/hsec-tools/src/Security/OSV.hs
Update OSV library to use `UTCTime` for the timestamp fields.
> lib/osv: use UTCTime for timestamp fields

- code/hsec-tools/flake.nix
- code/hsec-tools/hsec-tools.cabal
> deps: Cabal -> Cabal-syntax

- EXAMPLE_ADVISORY.md
- README.md
Fixes: https://github.com/haskell/security-advisories/issues/36
> doc: add keyword guidance

- meeting-notes/2023-07-12.md
> Add notes for 2023-07-12

- code/hsec-tools/app/Main.hs
- code/hsec-tools/hsec-tools.cabal
- code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
> feature(tools): Add index generation command (#31)

- advisories/hackage/hledger-web/HSEC-2023-0008.md
> HSEC-2023-0008: Stored XSS in hledger-web

- .github/workflows/check-advisories.yml
> fix(ci): adapt publish osv data

- meeting-notes/2023-09-20.md
> add meeting notes

- meeting-notes/2023-10-18.md
- meeting-notes/2023-11-01.md
> meeting notes: 2023-10-18, 2023-11-01

- .github/workflows/call-check-advisories.yml
> fix(ci): check-advisories cache miss breaks due to step call workflow call

- flake.nix
> fix(nix): don't ship dev tools within the production closure (#144)

- code/hsec-tools/app/Main.hs
- always show help on empty comand
- use `hsubparser`
---
- [ x Previous advisories are still valid
> [chore] some tiny improvements

- meeting-notes/2024-02-07.md
> meeting notes: 2024-02-07

- .github/workflows/nix.yml
- code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
> fix: try another action for GitHub Pages deployments

- meeting-notes/2024-03-06.md
> meeting notes: 2024-03-06

- code/hsec-tools/hsec-tools.cabal
- code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
> feature: add atom feed to GitHub Pages

- .github/workflows/call-check-advisories.yml
- .github/workflows/call-nix.yml
- .github/workflows/check-advisories.yml
- .github/workflows/haskell-ci.yml
- .github/workflows/nix.yml
Hopefully it won't break down this time
>  fix: fix check-advisories only GitHub Actions workflow 

- .github/haskell-ci.patch
- .github/workflows/call-check-advisories.yml
- .github/workflows/call-nix.yml
- .github/workflows/check-advisories.yml
- .github/workflows/haskell-ci.yml
- .github/workflows/nix.yml
- README.md
- code/hsec-core/src/Security/Advisories/Core/Advisory.hs
- code/hsec-tools/src/Security/Advisories/Parse.hs
- code/hsec-tools/test/Spec/QueriesSpec.hs
- code/hsec-tools/test/golden/EXAMPLE_ADVISORY.md.golden
> feature: add CAPEC field (#158)

- .github/workflows/nix.yml
> ci: fix osv data generation

- code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
I recommend to review it commit by commit.
---
> atom feed: more (hopefully uncontroversial) changes

- reports/2024-04-08-Q1-report.md
> reports: add 2024 Q1 report

- advisories/hackage/process/HSEC-2024-0003.md
> HSEC-2024-0003: mention GHC releases with fix

- guides/github.md
Follows #193, based on comments there.
> Update guide to secure GitHub CI

- meeting-notes/2024-05-01.md
> meeting notes: 2024-05-01

- meeting-notes/2024-06-12.md
> meeting notes: 2024-06-12

- meeting-notes/2024-07-10.md
> meeting notes: 2024-07-10

- meeting-notes/2024-07-24.md
> meeting notes: 2024-07-24

- meeting-notes/2024-10-02.md
> meeting notes: 2024-10-02

- code/hsec-tools/hsec-tools.cabal
cc @blackheaven @frasertweedale
> chore: Bump pandoc version in hsec-tools

- meeting-notes/2024-11-13.md
> meeting notes: 2024-11-13

- reports/2024-11-14-Q3-report.md
> reports: typospotting

- advisories/hackage/git-annex/HSEC-2023-0009.md
- advisories/hackage/git-annex/HSEC-2023-0010.md
> Update the introduced version for git-annex

- meeting-notes/2024-11-27.md
> meeting notes: 2024-11-27

- meeting-notes/2024-12-11.md
> meeting notes: 2024-12-11

- meeting-notes/2025-01-08.md
> meeting notes: 2025-01-08

- meeting-notes/2025-02-05.md
> meeting notes: 2025-02-05

- reports/2024-02-06-Q4-report.md
> reports: add 2024 Q4 report

- meeting-notes/2025-02-20.md
> meeting notes: 2025-02-20

- .github/workflows/haskell-ci.yml
- code/hsec-core/hsec-core.cabal
- code/hsec-sync/hsec-sync.cabal
- code/hsec-tools/hsec-tools.cabal
- code/hsec-tools/test/Spec.hs
- code/osv/osv.cabal
> Add GHC 9.12 support

- meeting-notes/2025-03-20.md
> meeting-notes: 2025-03-20

- advisories/hackage/xz-clib/HSEC-2025-0003.md
> HSEC-2025-0003: add fixed version

- meeting-notes/2025-04-30.md
> meeting-notes: 2025-04-30

- meeting-notes/2025-05-15.md
> meeting-notes: 2025-05-15
