.github/PULL_REQUEST_TEMPLATE.md

This adds a bit of Markdown formatting, fixes a typo, and removes the hyphens in "up to date" (see e.g. https://writingexplained.org/up-to-date-hyphenated for the rule)

Minor nitpicks in PR template

---

.github/PULL_REQUEST_TEMPLATE.md
code/hsec-tools/README.md

Since the file has been removed, we can remove the related instructions.

Remove cabal freeze leftover mentions

---

code/hsec-tools/src/Security/Advisories.hs

Fix `arch` value being read from `os` field (probably a copy/paste error).

tools: parse "arch" field

---

.github/workflows/check-advisories.yml

Add a CI check that HSEC ids (or the filenames, at least) are unique.
I pushed a branch with a conflict to test the new CI step.  Result:
https://github.com/frasertweedale/security-advisories/actions/runs/5251623664/jobs/9486797411

ci: check HSEC id uniqueness

---

advisories/hackage/aeson/HSEC-2023-0001.md

Add aeson hash flooding advisory.
This should put our CI through its paces.  Some other things to note/discuss:
Later, we could add merge automation to select the next appropriate `HSEC` identifier and update the commit before merging.  It's a "nice to have" and we can do it later.

HSEC-2023-0001: aeson hash flooding

---

.github/workflows/check-advisories.yml
code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal

Fixes: https://github.com/haskell/security-advisories/issues/40
```
commit 3598b43f1f4757763eb66c8ac7b1f9480b3a639d
Author: Fraser Tweedale <frase@frase.id.au>
Date:   Tue Jun 13 21:42:58 2023 +1000
tools(check): check filename matches advisory ID
We expect advisories in files name `HSEC-YYYY-NNNN.md`.  The
advisory ID also appears in the TOML metadata.  Add a check that the
ID is the same in both places.
If the filename does not match the expected pattern, we allow it.
The heuristic is ``"HSEC-" `isPrefixOf```, to allow for files that
do not match the pattern (for instance, example advisories).  This
is quite a crude heuristic, and should probably be improved
somewhat, to catch more subtle errors.  But this will do for now.
Fixes: https://github.com/haskell/security-advisories/issues/40 …

tools: check filename matches advisory ID

---

EXAMPLE_ADVISORY.md
README.md
advisories/hackage/aeson/HSEC-2023-0001.md
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories.hs
code/hsec-tools/src/Security/OSV.hs

This PR is based on #33, further refining the `Model` type and the encode/decode behaviour.
- Add `schema_version` field
- Add `withdrawn` field
- Add `credits` field (a `[Value]` for now, to be refined later)
- Make all optional fields optional
- Make `aliases` and `related` fields a list of strings (instead of arbitrary values)
- For list fields, interpret missing field as empty list (and omit empty lists when converting to JSON)
- Parameterise `Model` over the "database_specific" payload type. A naïve consumer can just use `Model Value`
- Add dedicated `ReferenceType` type

tools: OSV model improvements

---

code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories.hs

Instead of our hand-rolled document AST, parse the advisory content into a `Pandoc` document via *commonmark-pandoc*.  Store the `Pandoc` value in the `advisoryPandoc` field.
We continue (for now) to retain the `advisoryHtml` field.  It now displays the raw TOML block instead of a prettier HTML table - a mild regression.  But we expect to remove this field in the future, when we implement full site rendering for the advisory database.
Fixes: https://github.com/haskell/security-advisories/issues/43

lib/advisories: parse into pandoc AST

---

advisories/hackage/biscuit-haskell/HSEC-2022-0001.md

Report biscuit-haskell CVE-2022-31053 (#32)

---

CONTRIBUTING.md

This came up while following the instructions to test the project. The existing link just goes to the pull request section.

Update link to template on CONTRIBUTING.md

---

advisories/hackage/xmonad-contrib/HSEC-2023-0002.md
advisories/hackage/xmonad-contrib/HSEC-2023-0003.md

Report xmonad-contrib CVE-2013-1436

---

advisories/hackage/biscuit-haskell/HSEC-2023-0002.md

fix(advisory): rename HSEC-2022-0001 to HSEC-2023-0002

---

EXAMPLE_ADVISORY.md
README.md
advisories/hackage/aeson/HSEC-2023-0001.md
advisories/hackage/biscuit-haskell/HSEC-2023-0002.md
advisories/hackage/xmonad-contrib/HSEC-2023-0003.md
code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/Git.hs
code/hsec-tools/src/Security/Advisories/Parse.hs

***Note:** there are 4 nice, self-contained commits in this PR.  The best approach for review would be to review each commit in sequence.*
Update hsec-tools to read the publication and modification
timestamps from the Git history.  The heuristic uses the commit time
of the first appearance of the file as the publication date, and the
most recent commit that changed the file as the modification date.
Rewrites are followed at Git's default similarity threshold.
The behaviour to query the Git repository is provided in the new
module `Security.Advisories.Git`.
Failures running Git or parsing the output are ignored (e.g. if the
given file is not in a Git repository).  This supports use of the
tool outside the Git context.  The caveat is that the advisory TOML
header must have explicit `"date"` …

lib/advisories: read timestamps from Git history

---

code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/Parse.hs

Add the `advisoryDetails :: Text` field, which reflects the OSV `details` field.  It is intended to be CommonMark content.
When parsing, use a nasty hack to get the source range of the TOML header, so that we can drop it and store the remainder of the input as the `advisoryDetails`.

lib/advisories: add advisoryDetails field (and parse it)

---

code/hsec-tools/src/Security/OSV.hs

**Note**: several self-contained, sequential commits.  Recommend to review 
them in sequence.
```
2a81f0d (Fraser Tweedale, 8 minutes ago)
lib/osv: add dedicated Credit type
8a6f9dd (Fraser Tweedale, 35 minutes ago)
lib/osv: add Severity type
Use a proper type for `"severity"` scores.  There is further work to do to
adopt proper CVSS data types, but this change brings us closer to the OSV
schema.
Also add the `affected[].severity` field, which was missing.
f5d8631 (Fraser Tweedale, 28 hours ago)
lib/osv: refine Range and Event types
Update the `Range` and `Event` types to more accurately implement the OSV
schema.
```

lib/osv: improve types (Range, Event, Severity, Credit)

---

code/hsec-tools/src/Security/OSV.hs

**Note**: 4 self-contained, sequential commits.  Recommend to review each in sequence.
```
commit 4519a7605b20e57d3c0e0fab95d5862464c78fbb
Author: Fraser Tweedale <frase@frase.id.au>
Date:   Wed Jun 21 16:27:44 2023 +1000
lib/osv: abstract over database/ecosystem-specific fields
A general-purpose OSV library should not hardcode anything about the
`database_specific` or `ecosystem_specific` fields.  Abstract over
these.
A naïve consumer can parse `Model Value Value Value Value` for no
loss of information.
A producer can instantiate unused database/ecosystem-specific fields
at `Void`.  `()` is not recommended, because `Just ()` will
serialise as an empty JSON array.
commit c6a6d09ef5cbb91b18fd68b90a27968f9fa056a4
Author: Fraser Tweedale <frase@frase.id.au>
Date:   Thu Jun 22 23:31:14 2023 …
```

lib/osv: more schema alignment improvements, and other cleanups

---

advisories/hackage/xmonad-contrib/HSEC-2023-0003.md

Refine the type of an existing reference, and add a FIX reference.
Update the affected versions.  The fix version is actually v0.11.2, and the introduced version is v0.5 or *possibly earlier*.  A big refactor happened before v0.5 and I'm unsure if previous versions were affected.  In any case, v0.5 is the earliest version on Hackage.

HSEC-2023-0003: update versions and references

---

code/hsec-tools/flake.lock
code/hsec-tools/flake.nix

fix(tool): rely on nixos-unstable to use cache

---

EXAMPLE_ADVISORY.md
README.md
advisories/hackage/aeson/HSEC-2023-0001.md
advisories/hackage/biscuit-haskell/HSEC-2023-0002.md
advisories/hackage/xmonad-contrib/HSEC-2023-0003.md
code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/Parse.hs

A single vulnerability in a particular package may manifest itself simultaneously across one or more dependent packages. In this case, it would be good to issue a single advisory, rather than multiple. The OSV schema reflects this reality. Every OSV object has a list of affected packages, possibly with differing CVSS scores.
Modify the TOML schema to accept multiple affected packages.  There is now an array of tables called `affected`.  The `package`, `cvss`, `arch`, `os` and `declarations` fields, and the `versions` table, become members of the `affected` elements.
Fixes: https://github.com/haskell/security-advisories/issues/65
---

lib/advisories: support multiple packages per advisory

---

code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/Parse.hs

Some scenarios require limiting the version range without a fix version.  Add support for the "limit" specifier, which is mutually exclusive witih "fix".

lib/advisories: add "limit" field for version ranges

---

code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/Parse.hs

The "related" field in our advisory format was documented but not implemented.  Implement it.

lib: add support for "related" field

---

code/hsec-tools/src/Security/Advisories/Convert/OSV.hs

`advisoryRelated` and OSV export were recently merged (separately). As a consequence, the "related" field is not included in the conversion.  Add it now.

tools: add "related" field to OSV export

---

.github/workflows/check-advisories.yml

***note:** the PR's CI job won't publish the advisories.  This is by design.  Only pushes to `main` will trigger the publish step.*
The osv.dev project will be enhanced to ingest OSV data from our advisory database.  One of the convenient formats for them is to track a Git branch containing the raw OSV data.
To facilitate this, add a CI step that exports the OSV data to the `generated/osv-export` branch.  This step only runs upon a push to `main`.  It exports all the advisories as OSV JSON files, sorted into directories by year.  Then it snapshots this content onto the `generated/osv-export` branch and pushes it.  The commit message contains a UTC timestamp, and the hash of the corresponding commit on `main`.
No commit is made unless the OSV content has changed.  The …

ci: publish OSV data to dedicated branch

---

EXAMPLE_ADVISORY.md

Fixes: https://github.com/haskell/security-advisories/issues/53

doc: add `references` explanation in example advisory

---

PROCESS.md

This PR imports the OpenStack VMT's process. The main differences are:
- We don't use an issue tracker with an easy to follow status fields or tags.
- Our mail addresses doesn't have associated gpg keys.
Thus I removed these parts from the original vmt-process, but perhaps we could also adopt these practices.
Moreover, we don't have a downstream stakeholder list yet. At the last meeting we talked about adding the relevant mails addresses to the repository, but we might want to consider a `embargo-notice@haskell.org` list instead.
Lastly, the vmt-process defines an `impact description` that is a subset of the final advisory. It seems like we could do the same by omitting the CVE and references. That way we can refer to the document that is being created before the CVE request.

Add PROCESS.md

---

.github/workflows/check-advisories.yml

Pushes to `main` in forks currently trigger OSV export.  This results in CI failures if the branch does not exist in the fork, and divergence from origin if it does.  Better to avoid this scenario and restrict the publish step to `haskell/security-advisories`.

ci: limit osv export to haskell/security-advisories

---

reports/2023-07-10-ann-q2-report.md

add the `reports/` directory and publish our first report there.

reports: add 2023 Q2 report / SRT announcement

---

code/hsec-tools/hsec-tools.cabal

Remove duplicate `Tested-With` declaration, and add upper bound for *aeson*.
**note**: I checked the build against the just-released `aeson-2.2.0.0` and it is fine.  We could put the upper bound at `< 2.3` if people prefer, instead of `< 3`.

hsec-tools.cabal: minor fixes

---

code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories.hs
code/hsec-tools/src/Security/Advisories/Convert/OSV.hs
code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/HsecId.hs
code/hsec-tools/src/Security/Advisories/Parse.hs

Add a data type for representing HSEC IDs.  In addition to better validation when parsing advisories, this is a step towards hsec-tools features for assigning and reserving IDs.

lib/advisories: add dedicated HsecId type

---

advisories/hackage/xml-conduit/HSEC-2023-0004.md

Chipping away at known historical issues.

HSEC-2023-0004: xml-conduit entity expansion attack

---

code/hsec-tools/src/Security/Advisories/Parse.hs

lib: make references array optional

---

advisories/hackage/tls-extra/HSEC-2023-0005.md

HSEC-2023-0005: tls-extra does not check BasicConstraints

---

code/hsec-tools/flake.lock
code/hsec-tools/flake.nix
code/hsec-tools/shell.nix

See #96 -- introduce `developPackage`, compat layer for `shell.nix` and some formatting. This fixes nix build/cache issues.
---

tools: improve nix caching

---

.github/workflows/check-advisories.yml
code/hsec-tools/src/Security/Advisories/Generate/HTML.hs

Advisories with multiple affected packages will be defined as a single file in the "lowest level" package directory, with inbound symbolic links of the same name in the other package directories.
Update the generate-index command to ignore symbolic links.  This prevents duplicate entries appearing in the lists/tables.

tools/index: ignore symlinks to avoid duplicate entries

---

.github/workflows/check-advisories-standalone.yml
.github/workflows/check-advisories.yml

The updated CI does not properly interpret the list of changed files so that only modified advisories get checked (when *only* advisories changed).
- The "changed files" list could include non-advisories (e.g.  CI workflow YAML files).  Update the `advisories_changed` job to output the filtered file list (as JSON).
- Remove the `changed_files` job.  It is not needed.  We output the matched files from the `advisories_changed` job.
- There were some `bash` command parsing errors when including the JSON in the command arguments.  Propagate it in environment variables instead.
- Finally, `$CHANGED_ADVISORIES` outputs only the first element of the array.  Use `printf` to print the array, one file per line.
---

ci: properly handle multiple changed advisories

---

advisories/hackage/aeson/HSEC-2023-0001.md
advisories/hackage/biscuit-haskell/HSEC-2023-0002.md
advisories/hackage/hledger-web/HSEC-2023-0008.md
advisories/hackage/tls-extra/HSEC-2023-0005.md
advisories/hackage/x509-validation/HSEC-2023-0006.md
advisories/hackage/xml-conduit/HSEC-2023-0004.md
advisories/hackage/xmonad-contrib/HSEC-2023-0003.md

Historical advisories report issues that were disclosed and fixed before the HSEC advisory database existed.  For accurate statistics about contemporary security issues in the Haskell ecosystem, add the "historical" keyword to such advisories.  We can use it to filter advisories.
---

add keyword to indicate "historical" advisories

---

.gitignore

fix(git): adapt gitignore after flake move

---

code/hsec-tools/app/Main.hs

Add descriptions for each of the subcommands.  These will appear in the help/usage output.
Also add `helper` (the `-h/--help` option) to two subcommands that were missing it.

tools: improve CLI help

---

advisories/hackage/pandoc/HSEC-0000-0000.md
advisories/hackage/pandoc/HSEC-2023-0014.md

Hey all, was going through some advisories I've been tracking and noticed you were missing one that I had. Hope I followed the format correctly for adding an advisory
Source report:
https://github.com/jgm/pandoc/security/advisories/GHSA-xj5q-fv23-575g
---

Add GHSA-xj5q-fv23-575g for pandoc

---

.github/workflows/haskell-ci.yml
code/hsec-tools/README.md
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/test/Spec.hs
code/hsec-tools/test/golden/EXAMPLE_ADVISORY.md
code/hsec-tools/test/golden/EXAMPLE_ADVISORY.md.golden
code/hsec-tools/test/golden/MISSING_AFFECTED.md
code/hsec-tools/test/golden/MISSING_AFFECTED.md.golden
code/hsec-tools/test/golden/MISSING_TITLE.md
code/hsec-tools/test/golden/MISSING_TITLE.md.golden

tools: add golden tests to validate the parser

---

PROCESS.md

Add lists for privately disclosing vulns downstream

---

.github/workflows/check-advisories.yml
code/hsec-tools/app/Command/Reserve.hs
code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories/Filesystem.hs
code/hsec-tools/src/Security/Advisories/Git.hs
code/hsec-tools/src/Security/Advisories/HsecId.hs

***note*** this PR consists of several commits.  I recommend to review
them separately, in chronological order, as they step by step introduce
the supporting library code and then the feature.
This PR adds the `reserve-id` command, which requests or assigns an HSEC
ID reservation.  It can also commit the change, ready for the
contributor to push and create a pull request.
Reservations are empty files under advisories/reserved.
CI enforces uniqueness.  When reservations get replaced with a full
advisory the reservation file must be removed in the same commit.
Reservation files SHOULD be empty, but nothing enforces that (yet).
Fixes: https://github.com/haskell/security-advisories/issues/110
---

hsec-tools: add reserve command

---

code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories/Convert/OSV.hs
code/hsec-tools/src/Security/Advisories/Definition.hs
code/hsec-tools/src/Security/Advisories/Filesystem.hs
code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
code/hsec-tools/src/Security/Advisories/Parse.hs
code/hsec-tools/src/Security/Advisories/Queries.hs
code/hsec-tools/test/Spec.hs
code/hsec-tools/test/Spec/QueriesSpec.hs
code/hsec-tools/test/golden/EXAMPLE_ADVISORY.md.golden

feature: add query command to check wheter a package/version is affected

---

advisories/hackage/cabal-install/HSEC-2023-0015.md

Add advisory for cabal-install key policy expiration check issue.
Heads-up @gbaz @Kleidukos - please review the advisory content and let us know if it needs tweaking.

HSEC-2023-0015: cabal-install uses expired key policy

---

code/hsec-tools/src/Security/OSV.hs

"type" and "score" fields were mixed up.  Put them straight.
Fixes: https://github.com/haskell/security-advisories/issues/135
---

osv: fix ToJSON encoding of Severity object

---

code/hsec-tools/hsec-tools.cabal
code/hsec-tools/test/Spec.hs
code/hsec-tools/test/golden/EXAMPLE_ADVISORY.md.golden
code/hsec-tools/test/golden/MISSING_AFFECTED.md.golden
code/hsec-tools/test/golden/MISSING_TITLE.md.golden

This change prevents regression in the OSV output.

Add OSV export golden test

---

code/hsec-tools/src/Security/Advisories/Generate/HTML.hs

fix: generate .nojekyll with index to activate GitHub pages

---

code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories/Parse.hs
code/hsec-tools/test/golden/MISSING_AFFECTED.md.golden
flake.lock
flake.nix

This new version provides native Text support and mapping schema errors back to source positions.
---

Support toml-parser-2.0.0.0

---

advisories/hackage/keter/HSEC-2024-0001.md

Hi SRT! Absolutely cool undertaking; please keep it going. Here're my 5 cents.
Evaluating XSS impacts in CVSS v3.1 is rather tricky, esp. in generic context of an app-server; I took guidance from [this post][1], and IMO lowish-medium severity seems about right.
No CVE was requested; disclosure and fix happened in 2022. `keywords += ["historic"]` ?
Please review & merge.
cc @jappeace hey, look what now exists :heart_eyes: https://haskell.github.io/security-advisories/
[1]: https://security.stackexchange.com/questions/271753/cvss3-score-for-xss-leading-to-account-takeover
---

HSEC-2024-0001: host header rXSS in keter

---

.github/workflows/nix.yml

fix: simplify nix CI to avoid GHA cache

---

code/hsec-tools/src/Security/Advisories/Generate/HTML.hs

atom feed compliance fixes

---

code/hsec-tools/src/Security/Advisories/Generate/HTML.hs

atom: set updated to newest advisory modification date, not oldest

---

advisories/hackage/process/HSEC-2024-0003.md

HSEC-2024-0003: process: command injection on Windows

---

advisories/hackage/process/HSEC-2024-0003.md

HSEC-2024-0003: add acknowledgements + other improvements

---

advisories/hackage/process/HSEC-2024-0003.md

HSEC-2024-0003: alias CVE-2024-3566, add references

---

guides/github.md

I'm not sure of where to place this. I made a new directory, but leaving to review to decide if we want this in the root directory or somewhere else. My thinking was that we can add other guides too as we go along, for example when we identify common vulnerable patterns in code.

Add guide to secure GitHub workflows

---

guides/github.md

This should incorporate remaining feedback from @hasufell (in #193), but happy to incorporate any new feedback that arises.
Thank you.

Update GitHub guide to incorporate remaining feedback

---

code/hsec-core/hsec-core.cabal
code/hsec-sync/hsec-sync.cabal
code/hsec-tools/hsec-tools.cabal
code/osv/osv.cabal

Add missing version bounds on `cvss`, and update maintainer.
---

osv: update package metadata

---

CONTRIBUTING.md
PROCESS.md

Our guidelines are out of date.  Update to reflect the current SRT
disposition w.r.t. embargoes.
Fixes: https://github.com/haskell/security-advisories/issues/204

doc: clarify embargo disposition

---

cabal.project
code/hsec-core/hsec-core.cabal
code/hsec-core/src/Security/Advisories/Core/Advisory.hs
code/hsec-sync/hsec-sync.cabal
code/hsec-tools/app/Main.hs
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/src/Security/Advisories/Convert/OSV.hs
code/hsec-tools/src/Security/Advisories/Filesystem.hs
code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
code/hsec-tools/src/Security/Advisories/Git.hs
code/hsec-tools/src/Security/Advisories/Parse.hs
code/hsec-tools/test/Spec.hs
flake.lock
flake.nix

- introduce Exception instance for ParseAdvisoryError
- display if parsing out of band git attributes failed
- also try to parse into a UTCTime **instead** of a ZonedTime
resolves #203 
resolves #202 
resolves #200 
---

[fix] some minor fixes

---

advisories/hackage/xmonad-contrib/HSEC-2023-0003.md
code/cvss/CHANGELOG.md
code/cvss/cvss.cabal
code/cvss/src/Security/CVSS.hs
code/cvss/test/Spec.hs
code/hsec-core/hsec-core.cabal
code/hsec-tools/hsec-tools.cabal
code/hsec-tools/test/Spec/FormatSpec.hs
code/osv/osv.cabal

This change fix the OSV export.
Fixes #217

Remove CVSS v2 prefix from vector string

---

code/hsec-tools/src/Security/Advisories/Filesystem.hs
code/hsec-tools/src/Security/Advisories/Queries.hs

The `listAdvisories` error type is `[ParseAdvisoryError]`.  The error values do not have context indicating the file that caused the error.  As a result, the error message(s) do not point to the problematic file(s).
Update the error type to `[(FilePath, ParseAdvisoryError)]`; each parse error is paired with the path to the problematic file.  As a result, user error messages are much more useful.
---

hsec-tools: include affected FilePath with parse errors

---

code/hsec-tools/src/Security/Advisories/Generate/HTML.hs

Presentation of packages/components that have multiple advisories is corrupted, due to missing <tr> parent elements.  Data cells for multiple advisories are appearing in a single row.  Add missing <tr> elements.
Before:
After:
---

html: fix missing <tr> on by-packages index

---

code/hsec-core/src/Security/Advisories/Core/Advisory.hs
code/hsec-tools/app/Main.hs
code/hsec-tools/src/Security/Advisories/Convert/OSV.hs
code/hsec-tools/src/Security/Advisories/Filesystem.hs
code/hsec-tools/src/Security/Advisories/Format.hs
code/hsec-tools/src/Security/Advisories/Generate/HTML.hs
code/hsec-tools/src/Security/Advisories/Parse.hs
code/hsec-tools/src/Security/Advisories/Queries.hs
code/hsec-tools/test/Spec.hs
code/hsec-tools/test/Spec/FormatSpec.hs
code/hsec-tools/test/Spec/QueriesSpec.hs
code/hsec-tools/test/golden/EXAMPLE_ADVISORY.md.golden

This change adds a new OOB to pass the Ecosystem value from the advisory path.
Fixes #212

Add Advisory.Ecosystem to support GHC's advisory

---

advisories/hackage/keter/HSEC-2024-0001.md

Other historical advisories use keyword "historical" rather than "historic".  Align HSEC-2024-0001 with this convention.
On the difference between "historic" and "historical", see https://en.wiktionary.org/wiki/historical#Usage_notes.
---

HSEC-2024-0001: update keywords: historic -> historical

---

EXAMPLE_ADVISORY.md
README.md
code/hsec-tools/app/Command/NextID.hs
code/hsec-tools/app/Command/Reserve.hs
code/hsec-tools/app/Main.hs
code/hsec-tools/app/Util.hs
code/hsec-tools/hsec-tools.cabal

Add `hsec-tools next-id` command, which prints the next available HSEC ID.
Also perform a minor refactor, extracting repo directory checks to a common utility function.

add next-id command

---

code/hsec-core/hsec-core.cabal
code/hsec-tools/hsec-tools.cabal

bump upper bounds for Cabal-syntax in `hsec-{core,tools}`
---

[chore] bump upper bound for Cabal-syntax in hsec-{core,tools}

---

meeting-notes/2024-09-04.md

meeting notes: 2024-09-04

---

code/hsec-sync/hsec-sync.cabal
code/hsec-tools/hsec-tools.cabal
code/osv/osv.cabal

chore: bump major dependencies (hsec-tools, hsec-sync, osv)

---

EXAMPLE_ADVISORY.md
README.md

doc: update examples to explain ghc-component and aliases

---

meeting-notes/2024-10-16.md

meeting notes: 2024-10-16

---

reports/2024-11-14-Q3-report.md

Finally got this done - sorry for the delay!  I included the announcement of new SRT members in the report.
---

reports: add 2024 Q3 report

---

advisories/hackage/process/HSEC-2024-0003.md

minor update to document that the fixed version of process was included in GHC 9.8.3, which was released in October.

HSEC-2024-0003: advise fixed in GHC 9.8.3

---

README.md
docs/README.md
docs/call-for-volunteers-example.md
docs/membership.md
docs/reports.md

Document various administrative processes within the SRT.

doc: SRT administrative processes

---

code/hsec-tools/assets/css/default.css
code/hsec-tools/src/Security/Advisories/Generate/HTML.hs

I have reworked advisory page for the index:
---

feat: rework index's advisory page

---

.github/workflows/nix.yml

Add OSV schema validation

---

advisories/ghc/ghc/HSEC-2025-0001.md

Add HSEC-2025-0001 GHC Subword division operations

---

advisories/ghc/ghc/HSEC-2024-0007.md
advisories/ghc/ghc/HSEC-2024-0008.md
advisories/hackage/base/HSEC-2024-0006.md

 Add advisories for numeric bugs in GHC 

---

advisories/hackage/crypton/HSEC-2025-0002.md
advisories/hackage/cryptonite/HSEC-2025-0002.md

---
Discussed here: https://github.com/awakesecurity/gen-ed25-keypair/issues/8#issuecomment-2745975829

advisory: Double Public Key Signing Function Oracle Attack on Ed25519

---

advisories/hackage/xz-clib/HSEC-2025-0003.md

Closes: https://github.com/haskell/security-advisories/issues/270 
---

HSEC-2025-0003: add xz-clib advisory

---

advisories/hackage/spacecookie/HSEC-2025-0004.md

HSEC-2025-0004: add spacecookie library vulnerability

---

meeting-notes/2025-05-28.md
meeting-notes/2025-06-12.md

Also correct the "previously" link in the 2025-05-28 meeting notes.
---

meeting-notes: 2025-06-12

---

docs/README.md
docs/membership.md
docs/packages.md
docs/reports.md

docs: document SRT packages and maintainership policies
